[2.0.0] 온보딩 연결 로직
ku-ring/app-ios-v2 pull request #185
Opened 2024-03-26 13:57 UTC by lgvv

## 내용
 - 온보딩 화면 확인했을 시, 두 번 나타나지 않도록 수정

2024-03-26 14:02 UTC, x-0o0 commented on KuringApp/KuringApp/KuringApp.swift
> +        _showsOnboarding = .init(initialValue: !commons.showsOnboarding())
이러면 학과정보를 가져오기전에 온보딩이 뜨게 되어 오류가 발생할 여지가 있습니다.

onCompletion에서 처리해주세요

2024-03-26 15:43 UTC, lgvv commented on KuringApp/KuringApp/KuringApp.swift
> +        _showsOnboarding = .init(initialValue: !commons.showsOnboarding())
수정했습니다.

2024-03-26 21:04 UTC, x-0o0 requested changes
1. 네이밍이 난해하여 간단한 로직인데도 이해하는데 여러 차례 반복해서 봐야했습니다. 정확한 네이밍이 필요합니다.
2. 온보딩 완료 여부를 학과 선택 전에 하는데 이 정책이 안드로이드도 동일한지 궁금합니다.

2024-03-26 21:04 UTC, x-0o0 commented on KuringApp/KuringApp/KuringApp.swift
> +                            if !commons.showsOnboarding() {
API description에는 온보딩이 필요한지 여부라고 되어있는데
실제동작은 반대군요..??

"만약 온보딩이 필요 없다면 온보딩을 띄워줘"

2024-03-26 21:04 UTC, x-0o0 commented on package-kuring/Sources/Caches/Dependency/Commons.swift
> +    @AppStorage(StringSet.isOnboarding)
어떤건 UserDefault 인데 이것만 AppStorage 쓰고 있습니다. 하나로 통일하는 것이 어떨까요

2024-03-26 21:04 UTC, x-0o0 commented on package-kuring/Sources/Caches/Dependency/Commons.swift
> +    public var showsOnboarding: () -> Bool
`needsOnboarding` 이 더 나아보입니다

2024-03-26 21:04 UTC, x-0o0 commented on KuringApp/KuringApp/KuringApp.swift
> +                            }
```suggestion
                            showsOnboarding = commons.needsOnboarding
```

2024-03-26 21:04 UTC, x-0o0 commented on package-kuring/Sources/Caches/Dependency/Commons.swift
> +    static var isOnboarding: Bool = false
네이밍만 보면
"Self 가 온보딩인지 여부" 이라 로직이해에 방해가 됩니다.
정확한 네이밍이 필요합니다.

2024-03-26 21:04 UTC, x-0o0 commented on package-kuring/Sources/Caches/Dependency/Commons.swift
> +    static var isOnboarding: Bool = false
`isOnboardingCompleted`이나 통일성 있게
`needsOnboarding`
이 좋아보입니다

2024-03-26 21:04 UTC, x-0o0 commented on package-kuring/Sources/Caches/Dependency/Commons.swift
>          }, changeOnboarding: { isOnboarding in
```swift
completeOnboarding: {
    Self.needsOnboarding = true
}
```
이렇게 하는게 네이밍도 보기 쉽고 로직도 명확한거 같아요.

현재는 인자를 받아서 처리하는 로직이 필요가 없는데 만약 인자를 받아서 처리하고 싶다면
```swift
updateOnboardingStatus: { needed in
    Self.needsOnboarding = needed
}
```

2024-03-26 21:04 UTC, x-0o0 commented on package-kuring/Sources/UIKit/OnboardingUI/OnboardingView/OnboardingView.swift
> +                    commons.changeOnboarding(true)
```suggestion
                    commons.updateOnboardingStatus(true)
```
또는
```suggestion
                    commons.completeOnboarding()
```

2024-03-26 21:04 UTC, x-0o0 commented on package-kuring/Sources/UIKit/OnboardingUI/OnboardingView/OnboardingView.swift
> +                    commons.changeOnboarding(true)
(질문)
학과 선택까지 완료했을 때가 아닌 학과 선택으로 넘어갈때 온보딩이
끝났다고 판단하는 이유가 궁금합니다.
이 부분이 안드로이드도 동일한가요~??

2024-03-27 12:01 UTC, lgvv commented on package-kuring/Sources/Caches/Dependency/Commons.swift
> +    public var showsOnboarding: () -> Bool
`needsOnboarding`로 수정했습니다.

2024-03-27 12:05 UTC, lgvv commented on package-kuring/Sources/Caches/Dependency/Commons.swift
> +    static var isOnboarding: Bool = false
제안주신 부분 중에 `needsOnboarding`도 작성해 보았는데, 컴파일에서 문제가 되지는 않지만 네이밍이 겹쳐서 헷갈릴수도 있겠다는 생각이 들어서 `isOnboardingCompleted`로 수정했습니다.

2024-03-27 12:12 UTC, lgvv commented on package-kuring/Sources/Caches/Dependency/Commons.swift
>          }, changeOnboarding: { isOnboarding in
리턴 타입이 `Bool`이라서 `needs`로 시작해야 좋지 않을까 했었는데, `completeOnboarding`로 수정했습니다.

`updateOnboardingStatus`가 확실히 더 명확해 보입니다. 온보딩 `Dependency`를 독립적으로 만들때는 몰랐는데, 인자를 받을 필요가 없어서 제거했습니다~!

2024-03-27 12:18 UTC, lgvv commented on package-kuring/Sources/UIKit/OnboardingUI/OnboardingView/OnboardingView.swift
> +                    commons.changeOnboarding(true)
음,, 학과 선택은 옵셔널하다고 생각해서 사용자다 온보딩 화면을 내리는 액션이 들어올 경우에 넣었었는데, 이 플로우는 오늘 희의에서 이야기해보면 좋을 것 같습니다.

(현재로직)
 - 사용자가 가이던스 3페이지까지 확인
    - 바로 시작하기 (온보딩 확인 상태 변경)
    - 학과 설정 (온보딩 확인 상태 변경) 
    



/cc @mwy3055

2024-03-27 12:27 UTC, lgvv commented on KuringApp/KuringApp/KuringApp.swift
> +                            if !commons.showsOnboarding() {
`isCompleteOnboarding`으로 수정했습니다

2024-03-27 15:36 UTC, lgvv commented on package-kuring/Sources/Caches/Dependency/Commons.swift
> +    @AppStorage(StringSet.isOnboarding)
통일했습니다~!

2024-03-27 15:36 UTC, x-0o0 approved these changes
LGTM

2024-03-27 15:37 UTC, x-0o0 commented
/쿠링 머지

2024-03-27 15:37 UTC, merged